spring.application.name=gestor_documental
spring.datasource.url=jdbc:mysql://localhost:3306/gestor_documental
spring.datasource.username=root
spring.datasource.password=samuelin1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

