

logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.orm.jdbc.bind=warn

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-swallow-size=50MB
server.tomcat.max-part-count=-1
server.tomcat.max-part-header-size=4096
server.tomcat.max-parameter-count=-1

logging.level.org.springframework.web=INFO
app.ocr.tessdataPath=${TESSDATA_PATH:C:/Tesseract/Tesseract-OCR/tessdata}
app.ocr.language=spa
app.ocr.dpi=300

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

app.initial-admin.email=${APP_ADMIN_EMAIL:}
app.initial-admin.password=${APP_ADMIN_PASSWORD:}