import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowRight, BellRing, History, RotateCcw } from "lucide-react";
import { Link } from "react-router-dom";
import { useConfirmDialog } from "../../../shared/ui/ConfirmDialog";
import { PaginationBar } from "../../listados/components/PaginationBar";
import { getExpedienteListCatalogs } from "../../listados/services/listadosApi";
import { archivarSeguimiento, getSeguimientos, reactivarSeguimiento } from "../services/seguimientoApi";
import type { Seguimiento } from "../types";

export function SeguimientoClientesPage() {
  const [vista, setVista] = useState("PENDIENTES"); const [clienteId, setClienteId] = useState(""); const [anio, setAnio] = useState(""); const [pagina, setPagina] = useState(0); const [tamanio, setTamanio] = useState(25); const qc = useQueryClient(); const { confirm, dialog } = useConfirmDialog();
  const query = useQuery({ queryKey: ["seguimiento", vista, clienteId, anio, pagina, tamanio], queryFn: () => getSeguimientos({ vista, clienteId, anio, pagina, tamanio }) }); const catalogs = useQuery({ queryKey: ["expedientes", "catalogos-listado"], queryFn: getExpedienteListCatalogs });
  const action = useMutation({ mutationFn: async ({ type, item }: { type: string; item: Seguimiento }) => type === "archivar" ? archivarSeguimiento(item.incidenciaId) : reactivarSeguimiento(item.incidenciaId), onSuccess: () => { qc.invalidateQueries({ queryKey: ["seguimiento"] }); qc.invalidateQueries({ queryKey: ["tareas"] }); } });
  async function run(type: string, item: Seguimiento) { const ok = await confirm({ title: type === "archivar" ? "Archivar seguimiento" : "Reactivar seguimiento", description: type === "archivar" ? "Dejara de generar recordatorios mientras el expediente siga abierto." : "Volvera a la bandeja de tareas para poder notificarlo.", confirmLabel: type === "archivar" ? "Archivar" : "Reactivar", tone: type === "archivar" ? "danger" : "default" }); if (ok) action.mutate({ type, item }); }
  const data = query.data; const years = Array.from({ length: 8 }, (_, i) => new Date().getFullYear() - i);
  return <main className="records-page followup-page"><header className="records-header"><div><p className="eyebrow">Control de esperas</p><h2>Seguimiento de clientes</h2><p>Incidencias notificadas pendientes de respuesta y seguimientos archivados que siguen vigentes.</p></div><span className="records-count">{data?.totalElementos ?? 0} casos</span></header>
    <div className="task-tabs"><button className={vista === "PENDIENTES" ? "is-active" : ""} onClick={() => { setVista("PENDIENTES"); setPagina(0); }} type="button"><BellRing size={15} /> Esperando respuesta</button><button className={vista === "ARCHIVADAS" ? "is-active" : ""} onClick={() => { setVista("ARCHIVADAS"); setPagina(0); }} type="button"><Archive size={15} /> Archivadas</button></div>
    <div className="task-filters"><label><span>Cliente</span><select value={clienteId} onChange={e => { setClienteId(e.target.value); setPagina(0); }}><option value="">Todos los clientes</option>{catalogs.data?.clientes.map(c => <option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label><span>Año expediente</span><select value={anio} onChange={e => { setAnio(e.target.value); setPagina(0); }}><option value="">Todos los años</option>{years.map(y => <option key={y}>{y}</option>)}</select></label></div>
    <section className="records-panel records-panel--ledger">{query.isLoading ? <div className="records-skeleton"><span /><span /><span /></div> : null}<div className="followup-list">{data?.contenido.length === 0 ? <div className="records-empty"><History size={24} /><strong>No hay seguimientos en esta vista.</strong></div> : null}{data?.contenido.map(item => <article className="followup-row" key={item.incidenciaId}><div><strong>{item.matricula || `EXP-${item.expedienteId}`}</strong><small>{item.cliente || "Sin cliente"}</small></div><div><strong>{format(item.tipoIncidencia)}</strong><span>{item.observaciones || "Sin observaciones"}</span></div><div><small>Avisos</small><strong>{item.avisosEnviados} / 5</strong><span>{item.fechaUltimoAviso || "Sin fecha"}</span></div><div><small>{vista === "ARCHIVADAS" ? "Archivada" : "Proximo vencimiento"}</small><strong>{vista === "ARCHIVADAS" ? item.fechaArchivo || "Sin fecha" : item.proximoAviso || "Sin fecha"}</strong></div><div className="followup-row__actions">{vista === "PENDIENTES" ? <button className="icon-button" title="Archivar" onClick={() => run("archivar", item)} type="button"><Archive size={16} /></button> : <button className="soft-button soft-button--compact" onClick={() => run("reactivar", item)} type="button"><RotateCcw size={15} /> Reactivar</button>}<Link className="icon-button" title="Ver expediente" to={`/expedientes/${item.expedienteId}`}><ArrowRight size={16} /></Link></div></article>)}</div><PaginationBar page={data?.pagina ?? 0} totalPages={data?.totalPaginas ?? 0} totalItems={data?.totalElementos ?? 0} pageSize={data?.tamanio ?? 25} onPageChange={setPagina} onPageSizeChange={s => { setTamanio(s); setPagina(0); }} /></section>{dialog}</main>;
}

const format = (value?: string | null) => value ? value.replaceAll("_", " ") : "INCIDENCIA";
