package com.example.gestor_documental.enums;

public enum AccionAuditoriaDocumento {
    VISUALIZAR,
    DESCARGAR,
    ELIMINAR,
    ELIMINAR_PAGINAS,
    EXPORTAR_HISTORIAL,
    EXPORTAR_GA,
    USUARIO_CREAR,
    USUARIO_ACTUALIZAR,
    USUARIO_ELIMINAR,
    ADMINISTRADOR_CLIENTE_CREAR,
    ADMINISTRADOR_CLIENTE_ACTUALIZAR,
    ADMINISTRADOR_CLIENTE_DESVINCULAR
}
