package com.example.gestor_documental.enums;

public enum CodigoHitoExpediente {
    TRAMITE_PROGRAMA_GESTION,
    MODELO_620_PRESENTADO,
    ENVIADO_DGT,
    BATE_TRAMITE_PROGRAMA_GESTION,
    BATE_MODELO_620_PRESENTADO,
    BATE_FINALIZADO,
    COM_TRAMITE_PROGRAMA_GESTION,
    COM_MODELO_620_PRESENTADO,
    COM_ENVIADO_DGT,
    COM_FINALIZADO
}
