package com.example.gestor_documental.enums;

public enum EstadoExpediente {
    EN_TRAMITE,
    INCIDENCIA,
    FINALIZADO,
    RECHAZADO,
    ENVIADO_DGT,
    REVISANDO_INCIDENCIAS,
    PENDIENTE_DOCUMENTACION,
    SOLICITADA_INFORMACION_ADICIONAL,
    INFORMACION_ADICIONAL_RECIBIDA
}
