package com.example.gestor_documental.enums;

public enum TipoDocumento {
    DNI, CONTRATO_COMPRAVENTA, FACTURA, PERMISO_CIRCULACION, FICHA_TECNICA, MANDATO, CAMBIO_TITULARIDAD, SOLICITUD_DGT, JUSTIFICANTE, HUELLA, OTROS
}
