import { apiGet, apiPost, apiPostForm, apiPutJsonResponse } from "../../../shared/api/http";
import type { AnalisisFactura, EstadoComprobante, FacturasPage, ModalidadFacturacion } from "../types";
export function listarFacturas(params:URLSearchParams){return apiGet<FacturasPage>(`/api/facturas?${params}`)}
export function sincronizarFacturas(){return apiPost("/api/facturas/sincronizar")}
export function aportarComprobante(id:number,archivo:File){const form=new FormData();form.append("archivo",archivo);return apiPostForm(`/api/facturas/${id}/comprobantes`,form)}
export function revisarComprobante(id:number,estado:EstadoComprobante){return apiPutJsonResponse(`/api/facturas/comprobantes/${id}`,{estado})}
export function abrirPdf(id:number){window.open(`/api/facturas/${id}/pdf`,"_blank","noopener,noreferrer")}
export function abrirComprobante(id:number){window.open(`/api/facturas/comprobantes/${id}/archivo`,"_blank","noopener,noreferrer")}
export async function descargarZip(ids:number[]){const response=await fetch("/api/facturas/zip",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(ids)});if(!response.ok)throw new Error("No se pudo preparar el ZIP");const url=URL.createObjectURL(await response.blob());const a=document.createElement("a");a.href=url;a.download="facturas.zip";a.click();URL.revokeObjectURL(url)}

export function analizarFacturas(archivos:File[]){const form=new FormData();archivos.forEach(a=>form.append("archivos",a));return apiPostForm<AnalisisFactura[]>("/api/facturas/analizar",form)}
export function confirmarFactura(input:{facturaId?:number;modalidad:ModalidadFacturacion;periodoDesde?:string;periodoHasta?:string;expedienteIds:number[];expedienteIdsManuales?:number[];archivo:File}){const form=new FormData();if(input.facturaId)form.append("facturaId",String(input.facturaId));form.append("modalidad",input.modalidad);if(input.periodoDesde)form.append("periodoDesde",input.periodoDesde);if(input.periodoHasta)form.append("periodoHasta",input.periodoHasta);input.expedienteIds.forEach(id=>form.append("expedienteIds",String(id)));input.expedienteIdsManuales?.forEach(id=>form.append("expedienteIdsManuales",String(id)));form.append("archivo",input.archivo);return apiPostForm<AnalisisFactura>("/api/facturas/confirmar",form)}