package com.example.gestor_documental.service.impl;
import com.example.gestor_documental.enums.*;import com.example.gestor_documental.exception.AccesoDenegadoException;import com.example.gestor_documental.model.*;import com.example.gestor_documental.repository.*;import com.fasterxml.jackson.databind.ObjectMapper;import com.sun.net.httpserver.HttpServer;import org.junit.jupiter.api.*;import org.springframework.mock.web.MockMultipartFile;import org.springframework.test.util.ReflectionTestUtils;import java.io.ByteArrayOutputStream;import java.net.InetSocketAddress;import java.nio.charset.StandardCharsets;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;
class HoldedFacturaServiceTest {
 @org.junit.jupiter.api.io.TempDir java.nio.file.Path tempDir;
 private FacturaHoldedRepository facturas;private ClienteRepository clientes;private ComprobantePagoRepository comprobantes;private FacturaExpedienteRepository links;private HoldedWebhookEventoRepository webhooks;private HoldedFacturaService service;private HttpServer server;
 @BeforeEach void setup()throws Exception{facturas=mock(FacturaHoldedRepository.class);clientes=mock(ClienteRepository.class);comprobantes=mock(ComprobantePagoRepository.class);links=mock(FacturaExpedienteRepository.class);webhooks=mock(HoldedWebhookEventoRepository.class);service=new HoldedFacturaService(facturas,clientes,comprobantes,links,mock(ExpedienteRepository.class),webhooks);server=HttpServer.create(new InetSocketAddress(0),0);ReflectionTestUtils.setField(service,"enabled",true);ReflectionTestUtils.setField(service,"apiToken","secret-backend-token");ReflectionTestUtils.setField(service,"apiBaseUrl","http://127.0.0.1:"+server.getAddress().getPort());ReflectionTestUtils.setField(service,"uploadDir",tempDir.toString());ReflectionTestUtils.setField(service,"syncYear",2026);ReflectionTestUtils.setField(service,"connectTimeoutSeconds",2);ReflectionTestUtils.setField(service,"readTimeoutSeconds",2);when(facturas.save(any())).thenAnswer(i->i.getArgument(0));when(clientes.findAll()).thenReturn(List.of());when(comprobantes.findByFacturaIdOrderByCreadoEnDesc(any())).thenReturn(List.of());}
 @AfterEach void stop(){if(server!=null)server.stop(0);}
 @Test void sincronizaYEmparejaPorNif(){Cliente c=cliente(7L,"B12345678");when(clientes.findAll()).thenReturn(List.of(c));when(clientes.findByHoldedContactId("contact-1")).thenReturn(Optional.empty());when(facturas.findByHoldedInvoiceId("inv-1")).thenReturn(Optional.empty());responder("/contacts","application/json","{\"items\":[{\"id\":\"contact-1\",\"code\":\"B-12345678\"}],\"has_more\":false}");responder("/invoices","application/json","{\"items\":[{\"id\":\"inv-1\",\"contact_id\":\"contact-1\",\"total\":100,\"payments_total\":40,\"status\":\"partial\",\"date\":\"2026-07-16\"}],\"has_more\":false}");server.start();assertEquals(1,service.sincronizarTodo().actualizadas());assertEquals("contact-1",c.getHoldedContactId());verify(facturas).saveAll(argThat(list->list.iterator().hasNext()&&list.iterator().next().getCliente()==c&&list.iterator().next().getEstado()==EstadoFacturaHolded.PARCIALMENTE_PAGADA));}
 @Test void sincronizaYEmparejaVatnumberConPrefijoDePais(){Cliente c=cliente(8L,"B12345678");when(clientes.findAll()).thenReturn(List.of(c));when(facturas.findByHoldedInvoiceId("inv-2")).thenReturn(Optional.empty());responder("/contacts","application/json","{\"items\":[{\"id\":\"contact-2\",\"vatnumber\":\"ES B-12345678\"}],\"has_more\":false}");responder("/invoices","application/json","{\"items\":[{\"id\":\"inv-2\",\"contact_id\":\"contact-2\",\"document_number\":\"2026/25\",\"total\":100,\"date\":\"2026-07-16\"}],\"has_more\":false}");server.start();assertEquals(1,service.sincronizarTodo().actualizadas());assertEquals("contact-2",c.getHoldedContactId());verify(facturas).saveAll(argThat(list->list.iterator().hasNext()&&list.iterator().next().getCliente()==c));}
 @Test void pdfYZipRespetanPermisos()throws Exception{Cliente c=cliente(8L,"X");FacturaHolded f=factura(3L,c,"inv-3");f.setArchivoFactura("local.pdf");java.nio.file.Path dir=tempDir.resolve("facturas");java.nio.file.Files.createDirectories(dir);java.nio.file.Files.writeString(dir.resolve("local.pdf"),"%PDF-test");when(facturas.findById(3L)).thenReturn(Optional.of(f));Usuario u=usuario(c);assertTrue(new String(service.descargarPdf(3L,u),StandardCharsets.UTF_8).startsWith("%PDF"));ByteArrayOutputStream zip=new ByteArrayOutputStream();service.descargarZip(List.of(3L),u,zip);assertTrue(zip.size()>10);assertThrows(AccesoDenegadoException.class,()->service.descargarPdf(3L,usuario(cliente(9L,"Y"))));}
 @Test void detalleClienteNoExponeDatosDeConciliacion(){Cliente c=cliente(8L,"X");FacturaHolded f=factura(6L,c,"inv-6");f.setTotal(java.math.BigDecimal.TEN);f.setImportePagado(java.math.BigDecimal.ZERO);Expediente e=new Expediente();e.setId(12L);e.setCliente(c);e.setMatricula("1234ABC");FacturaExpediente link=new FacturaExpediente();ReflectionTestUtils.setField(link,"id",4L);link.setFactura(f);link.setExpediente(e);link.setEstado(EstadoVinculacionFactura.CONFIRMADA);link.setMatriculaDetectada("DATO-INTERNO");link.setConfianza(98);when(facturas.findById(6L)).thenReturn(Optional.of(f));when(links.findByFacturaIdOrderByIdAsc(6L)).thenReturn(List.of(link));var detalle=service.detalle(6L,usuario(c));assertTrue(detalle.lineasPendientes().isEmpty());assertEquals(0,detalle.factura().lineasPendientesRevision());assertNull(detalle.vinculaciones().get(0).matriculaDetectada());assertEquals(0,detalle.vinculaciones().get(0).confianza());}
 @Test void comprobanteAjenoEsRechazado(){when(facturas.findById(5L)).thenReturn(Optional.of(factura(5L,cliente(1L,"A"),"inv")));MockMultipartFile file=new MockMultipartFile("archivo","pago.pdf","application/pdf",new byte[]{1});assertThrows(AccesoDenegadoException.class,()->service.aportarComprobante(5L,file,usuario(cliente(2L,"B"))));verifyNoInteractions(comprobantes);}
 @Test void webhookFirmadoEsIdempotente()throws Exception{byte[] payload="{\"id\":\"evt-1\"}".getBytes(StandardCharsets.UTF_8);ReflectionTestUtils.setField(service,"webhookSecret","webhook-secret");when(webhooks.existsByEventId("evt-1")).thenReturn(true);javax.crypto.Mac mac=javax.crypto.Mac.getInstance("HmacSHA256");mac.init(new javax.crypto.spec.SecretKeySpec("webhook-secret".getBytes(StandardCharsets.UTF_8),"HmacSHA256"));service.recibirWebhook("evt-1","sha256="+java.util.HexFormat.of().formatHex(mac.doFinal(payload)),payload);verify(webhooks,never()).save(any());}
 private void responder(String path,String type,String body){server.createContext(path,e->{assertEquals("Bearer secret-backend-token",e.getRequestHeaders().getFirst("Authorization"));if("/invoices".equals(path)){String query=e.getRequestURI().getQuery();assertTrue(query.contains("start_date=2026-01-01"));assertTrue(query.contains("end_date=2026-12-31"));}byte[] b=body.getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type",type);e.sendResponseHeaders(200,b.length);e.getResponseBody().write(b);e.close();});}
 private Cliente cliente(Long id,String nif){Cliente c=new Cliente();ReflectionTestUtils.setField(c,"id",id);c.setNif(nif);c.setNombre("C"+id);c.setEmail(id+"@x.es");return c;}private Usuario usuario(Cliente c){Usuario u=new Usuario();u.setRolUsuario(RolUsuario.CLIENTE);u.setCliente(c);u.getClientesAutorizados().add(c);return u;}private FacturaHolded factura(Long id,Cliente c,String remote){FacturaHolded f=new FacturaHolded();ReflectionTestUtils.setField(f,"id",id);f.setCliente(c);f.setHoldedInvoiceId(remote);f.setNumero("F-"+id);f.setEstado(EstadoFacturaHolded.PENDIENTE);return f;}
}

