CREATE TABLE expediente_lectura_ia_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    expediente_id BIGINT NOT NULL,
    creado_por_id BIGINT NULL,
    estado VARCHAR(30) NOT NULL,
    origen VARCHAR(40) NOT NULL,
    forzar_relectura BIT NOT NULL DEFAULT 0,
    total_items INT NOT NULL DEFAULT 0,
    items_procesados INT NOT NULL DEFAULT 0,
    items_revision INT NOT NULL DEFAULT 0,
    items_error INT NOT NULL DEFAULT 0,
    progreso INT NOT NULL DEFAULT 0,
    fase_actual VARCHAR(160) NULL,
    mensaje VARCHAR(1000) NULL,
    fecha_creacion DATETIME(6) NOT NULL,
    fecha_inicio DATETIME(6) NULL,
    fecha_fin DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exp_lectura_ia_job_expediente FOREIGN KEY (expediente_id) REFERENCES expediente(id),
    CONSTRAINT fk_exp_lectura_ia_job_usuario FOREIGN KEY (creado_por_id) REFERENCES usuario(id),
    INDEX idx_exp_lectura_ia_job_expediente_fecha (expediente_id, fecha_creacion),
    INDEX idx_exp_lectura_ia_job_estado_fecha (estado, fecha_creacion)
);

CREATE TABLE expediente_lectura_ia_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    job_id BIGINT NOT NULL,
    documento_id BIGINT NOT NULL,
    tipo_lectura VARCHAR(30) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    intentos INT NOT NULL DEFAULT 0,
    modelo VARCHAR(80) NULL,
    version_prompt VARCHAR(40) NULL,
    confianza DOUBLE NULL,
    mensaje VARCHAR(1000) NULL,
    fecha_inicio DATETIME(6) NULL,
    fecha_fin DATETIME(6) NULL,
    duracion_ms BIGINT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_exp_lectura_ia_item_job FOREIGN KEY (job_id) REFERENCES expediente_lectura_ia_job(id) ON DELETE CASCADE,
    CONSTRAINT fk_exp_lectura_ia_item_documento FOREIGN KEY (documento_id) REFERENCES documento(id),
    INDEX idx_exp_lectura_ia_item_job (job_id),
    INDEX idx_exp_lectura_ia_item_documento_fecha (documento_id, fecha_inicio),
    INDEX idx_exp_lectura_ia_item_estado (estado)
);
