CREATE TABLE auditoria_documento (
    id BIGINT NOT NULL AUTO_INCREMENT,
    fecha_evento DATETIME(6) NOT NULL,
    accion VARCHAR(30) NOT NULL,
    resultado VARCHAR(20) NOT NULL,
    documento_id BIGINT NULL,
    documento_nombre VARCHAR(200) NULL,
    documento_tipo VARCHAR(100) NULL,
    expediente_id BIGINT NULL,
    solicitud_id BIGINT NULL,
    cliente_id BIGINT NULL,
    usuario_id BIGINT NULL,
    usuario_email VARCHAR(150) NULL,
    usuario_rol VARCHAR(20) NULL,
    direccion_ip VARCHAR(64) NULL,
    agente_usuario VARCHAR(500) NULL,
    detalle VARCHAR(1000) NULL,
    PRIMARY KEY (id),
    INDEX idx_aud_doc_fecha (fecha_evento),
    INDEX idx_aud_doc_documento_fecha (documento_id, fecha_evento),
    INDEX idx_aud_doc_expediente_fecha (expediente_id, fecha_evento),
    INDEX idx_aud_doc_cliente_fecha (cliente_id, fecha_evento),
    INDEX idx_aud_doc_usuario_fecha (usuario_id, fecha_evento),
    INDEX idx_aud_doc_accion_resultado_fecha (accion, resultado, fecha_evento)
);
