import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useOutletContext } from "react-router-dom";
import { AlertTriangle, Check, ChevronDown, Download, FileArchive, FileCheck2, FileUp, RefreshCw, Search, ShieldCheck, X } from "lucide-react";
import type { AppOutletContext } from "../../../app/shell/AppLayout";
import { PaginationBar } from "../../listados/components/PaginationBar";
import { analizarFacturas, aportarComprobante, abrirComprobante, abrirPdf, confirmarFactura, descargarZip, listarFacturas, revisarComprobante, sincronizarFacturas } from "../services/facturasApi";
import type { AnalisisFactura, EstadoComprobante, EstadoFactura, ModalidadFacturacion } from "../types";
import "./facturas.css";

const etiquetas:Record<EstadoFactura,string>={PENDIENTE:"Pendiente",PARCIALMENTE_PAGADA:"Parcialmente pagada",PAGADA:"Pagada",ANULADA:"Anulada"};
const modalidades:Record<ModalidadFacturacion,string>={POR_EXPEDIENTE:"Por expediente",LOTE_QUINCENAL:"Lote quincenal",LOTE_MENSUAL:"Lote mensual"};

export function FacturasPage(){
  const {user}=useOutletContext<AppOutletContext>();
  const qc=useQueryClient();
  const [busqueda,setBusqueda]=useState(""); const [estado,setEstado]=useState(""); const [pagina,setPagina]=useState(0); const [tamanio,setTamanio]=useState(25); const [seleccion,setSeleccion]=useState<number[]>([]);
  const [archivos,setArchivos]=useState<File[]>([]); const [analisis,setAnalisis]=useState<AnalisisFactura[]>([]); const [modalidad,setModalidad]=useState<ModalidadFacturacion>("POR_EXPEDIENTE"); const [periodoDesde,setPeriodoDesde]=useState(""); const [periodoHasta,setPeriodoHasta]=useState("");
  const params=new URLSearchParams({pagina:String(pagina),tamanio:String(tamanio)}); if(busqueda)params.set("busqueda",busqueda); if(estado)params.set("estado",estado);
  const query=useQuery({queryKey:["facturas",params.toString()],queryFn:()=>listarFacturas(params)});
  const refresh=()=>qc.invalidateQueries({queryKey:["facturas"]});
  const sync=useMutation({mutationFn:sincronizarFacturas,onSuccess:refresh});
  const review=useMutation({mutationFn:({id,estado}:{id:number;estado:EstadoComprobante})=>revisarComprobante(id,estado),onSuccess:refresh});
  const analyze=useMutation({mutationFn:analizarFacturas,onSuccess:setAnalisis});
  const confirm=useMutation({mutationFn:confirmarFactura,onSuccess:()=>{refresh();setAnalisis([]);setArchivos([])}});
  const seguras=useMemo(()=>analisis.reduce((n,a)=>n+a.lineas.filter(l=>l.estado==="COINCIDENCIA_SEGURA").length,0),[analisis]);
  const upload=async(id:number,file?:File)=>{if(!file)return;await aportarComprobante(id,file);refresh()};
  const confirmar=(item:AnalisisFactura)=>{const file=archivos.find(a=>a.name===item.archivo);const expedienteIds=item.lineas.filter(l=>l.estado==="COINCIDENCIA_SEGURA"&&l.expedienteId).map(l=>l.expedienteId!);if(!file||!item.facturaId||!expedienteIds.length)return;confirm.mutate({facturaId:item.facturaId,modalidad,periodoDesde:modalidad==="POR_EXPEDIENTE"?undefined:periodoDesde,periodoHasta:modalidad==="POR_EXPEDIENTE"?undefined:periodoHasta,expedienteIds,archivo:file})};

  return <section className="invoice-ledger">
    <header className="invoice-ledger__hero"><div><p className="eyebrow">Contabilidad conectada</p><h2>Facturas</h2><p>Holded confirma importes y cobros. Los PDF y sus expedientes se concilian dentro de la gestoría.</p></div>{user?.rol==="ADMIN"?<div className="invoice-ledger__hero-actions"><label className="primary-button invoice-file-trigger"><FileUp size={16}/> Cargar facturas<input type="file" multiple accept="application/pdf" onChange={e=>{const next=Array.from(e.target.files||[]);setArchivos(next);setAnalisis([])}}/></label><button className="soft-button" disabled={sync.isPending} onClick={()=>sync.mutate()}><RefreshCw size={16}/> Sincronizar Holded</button></div>:null}</header>

    {user?.rol==="ADMIN"&&archivos.length?<section className="invoice-reconcile" aria-label="Conciliación de facturas"><div className="invoice-reconcile__heading"><div><p className="eyebrow">Mesa de conciliación</p><h3>{archivos.length} {archivos.length===1?"archivo preparado":"archivos preparados"}</h3><p>Se comprobarán número, fecha, matrícula, bastidor, comprador y justificantes finales.</p></div><button className="primary-button" disabled={analyze.isPending} onClick={()=>analyze.mutate(archivos)}><ShieldCheck size={17}/>{analyze.isPending?"Analizando…":"Analizar y proponer"}</button></div>{analyze.isError?<div className="alert alert--danger">No se pudieron analizar los PDF.</div>:null}
      {analisis.length?<><div className="invoice-reconcile__summary"><span><FileCheck2 size={18}/><strong>{seguras}</strong> coincidencias seguras</span><span><AlertTriangle size={18}/><strong>{analisis.reduce((n,a)=>n+a.lineas.filter(l=>l.estado!=="COINCIDENCIA_SEGURA").length,0)}</strong> para revisar</span><label>Modalidad<select value={modalidad} onChange={e=>setModalidad(e.target.value as ModalidadFacturacion)}>{Object.entries(modalidades).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><ChevronDown size={14}/></label>{modalidad!=="POR_EXPEDIENTE"?<><label>Desde<input type="date" value={periodoDesde} onChange={e=>setPeriodoDesde(e.target.value)}/></label><label>Hasta<input type="date" value={periodoHasta} onChange={e=>setPeriodoHasta(e.target.value)}/></label></>:null}</div><div className="invoice-analysis-grid">{analisis.map(item=><article className="invoice-analysis-card" key={item.archivo}><header><div><span>{item.estado.replaceAll("_"," ").toLowerCase()}</span><h4>{item.numeroFactura||item.archivo}</h4><small>{item.fechaFactura||"Fecha no detectada"} · {item.archivo}</small></div><button className="primary-button" disabled={!item.facturaId||!item.lineas.some(l=>l.estado==="COINCIDENCIA_SEGURA")||confirm.isPending||(modalidad!=="POR_EXPEDIENTE"&&(!periodoDesde||!periodoHasta))} onClick={()=>confirmar(item)}><Check size={15}/> Confirmar</button></header><div className="invoice-analysis-lines">{item.lineas.map((linea,index)=><div className={`invoice-match invoice-match--${linea.estado.toLowerCase()}`} key={`${linea.documento}-${index}`}><div><strong>{linea.matricula||"Sin matrícula"}</strong><small>{linea.documento} · {linea.bastidor||"Sin bastidor"}</small></div><div><span>Comprador</span><strong>{linea.compradorIdentificador||"No detectado"}</strong><small>{linea.compradorNombre}</small></div><div><span>Expediente</span><strong>{linea.expedienteId?`#${linea.expedienteId}`:"Sin asignar"}</strong><small>{linea.confianza}% confianza</small></div><div className="invoice-match__result">{linea.estado==="COINCIDENCIA_SEGURA"?<ShieldCheck size={17}/>:<AlertTriangle size={17}/>}<span>{linea.motivo||"Validación completa"}</span></div></div>)}</div></article>)}</div></>:null}
    </section>:null}

    <div className="invoice-ledger__filters"><label><Search size={16}/><input value={busqueda} onChange={e=>{setBusqueda(e.target.value);setPagina(0)}} placeholder="Número, cliente o NIF"/></label><select value={estado} onChange={e=>{setEstado(e.target.value);setPagina(0)}}><option value="">Todos los estados</option>{Object.entries(etiquetas).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className="soft-button" disabled={!seleccion.length} onClick={()=>descargarZip(seleccion)}><FileArchive size={16}/> Descargar ZIP ({seleccion.length})</button></div>
    {query.isLoading?<div className="empty-state">Cargando facturas…</div>:query.isError?<div className="alert alert--danger">No se pudieron cargar las facturas.</div>:<div className="invoice-table-wrap"><table className="invoice-table"><thead><tr><th><span className="sr-only">Seleccionar</span></th><th>Factura</th><th>Emisión</th><th>Cliente</th><th>Total</th><th>Estado Holded</th><th>Comprobantes</th><th></th></tr></thead><tbody>{query.data?.contenido.map(f=><tr key={f.id}><td><input type="checkbox" checked={seleccion.includes(f.id)} onChange={()=>setSeleccion(s=>s.includes(f.id)?s.filter(x=>x!==f.id):[...s,f.id])}/></td><td><strong>{f.numero||`#${f.id}`}</strong><small>Sincronizada {new Date(f.sincronizadaEn).toLocaleString("es-ES")}</small></td><td>{f.fechaEmision?new Date(`${f.fechaEmision}T00:00:00`).toLocaleDateString("es-ES"):"—"}</td><td>{f.contactoNombre||"Sin contacto"}<small>{f.contactoNif}</small></td><td className="invoice-table__amount">{new Intl.NumberFormat("es-ES",{style:"currency",currency:f.moneda||"EUR"}).format(f.total||0)}</td><td><span className={`invoice-state invoice-state--${f.estado.toLowerCase()}`}>{etiquetas[f.estado]}</span></td><td><div className="receipt-stack">{f.comprobantes.map(c=><div key={c.id}><button className="link-button" onClick={()=>abrirComprobante(c.id)}>{c.nombreOriginal}</button><span>{c.estado.replaceAll("_"," ").toLowerCase()}</span>{user?.rol==="ADMIN"&&c.estado==="PENDIENTE_VERIFICACION"?<span className="receipt-actions"><button aria-label="Verificar" onClick={()=>review.mutate({id:c.id,estado:"VERIFICADO"})}><Check size={14}/></button><button aria-label="Descartar" onClick={()=>review.mutate({id:c.id,estado:"DESCARTADO"})}><X size={14}/></button></span>:null}</div>)}<label className="receipt-upload"><FileUp size={14}/> Aportar<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>void upload(f.id,e.target.files?.[0])}/></label></div></td><td><button className="icon-button" aria-label="Abrir PDF de factura" onClick={()=>abrirPdf(f.id)}><Download size={17}/></button></td></tr>)}</tbody></table>{!query.data?.contenido.length?<div className="empty-state">No hay facturas con estos filtros.</div>:null}</div>}
    <PaginationBar page={query.data?.pagina||0} totalPages={query.data?.totalPaginas||0} totalItems={query.data?.totalElementos||0} pageSize={query.data?.tamanio||tamanio} onPageChange={setPagina} onPageSizeChange={(size)=>{setTamanio(size);setPagina(0)}}/>
  </section>
}