import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CalendarDays, Check, Download, FileUp, ReceiptText, Search, ShieldCheck, Trash2, TriangleAlert, WalletCards, X } from "lucide-react";
import { Link, useNavigate, useOutletContext, useParams } from "react-router-dom";
import type { AppOutletContext } from "../../../app/shell/AppLayout";
import { ApiError } from "../../../shared/api/http";
import { useConfirmDialog } from "../../../shared/ui/ConfirmDialog";
import { buscarGlobal } from "../../busqueda/services/busquedaGlobalApi";
import { abrirComprobante, abrirPdf, aportarComprobante, asignarLineaPendienteFactura, corregirVinculacionFactura, eliminarFactura, obtenerFacturaDetalle } from "../services/facturasApi";
import type { FacturaVinculacion, LineaFacturaPendiente } from "../types";
import "./facturas.css";

function CorregirExpediente({facturaId,vinculacion,onDone}:{facturaId:number;vinculacion:FacturaVinculacion;onDone:()=>void}){
  const [abierto,setAbierto]=useState(false); const [query,setQuery]=useState("");
  const search=useQuery({queryKey:["factura-correccion",query],queryFn:()=>buscarGlobal(query),enabled:abierto&&query.trim().length>=2,staleTime:30_000});
  const mutation=useMutation({mutationFn:(expedienteId:number)=>corregirVinculacionFactura(facturaId,vinculacion.id,expedienteId),onSuccess:()=>{setAbierto(false);setQuery("");onDone()}});
  if(!abierto)return <button className="link-button" type="button" onClick={()=>setAbierto(true)}>Cambiar expediente</button>;
  return <div className="invoice-correction"><div className="invoice-correction__input"><Search size={15}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} placeholder="Matrícula, interesado o EXP-ID"/><button type="button" onClick={()=>setAbierto(false)} aria-label="Cancelar"><X size={14}/></button></div>{query.trim().length>=2?<div className="invoice-correction__results">{search.isLoading?<small>Buscando…</small>:search.data?.expedientes.length?search.data.expedientes.map(item=>{const id=Number(item.id.replace(/\D/g,""));return <button key={item.id} type="button" disabled={mutation.isPending||id===vinculacion.expedienteId} onClick={()=>mutation.mutate(id)}><strong>{item.titulo} · {item.id}</strong><small>{item.detalle} · {item.meta}</small></button>}):<small>Sin coincidencias.</small>}</div>:null}{mutation.isError?<small className="invoice-correction__error">{mutation.error instanceof ApiError&&mutation.error.details?mutation.error.details:"No se pudo corregir la asignación."}</small>:null}</div>;
}

function AsignarPendiente({facturaId,linea,onDone}:{facturaId:number;linea:LineaFacturaPendiente;onDone:()=>void}){
  const [query,setQuery]=useState(linea.matricula||"");
  const search=useQuery({queryKey:["factura-pendiente",linea.indice,query],queryFn:()=>buscarGlobal(query),enabled:query.trim().length>=2,staleTime:30_000});
  const mutation=useMutation({mutationFn:(expedienteId:number)=>asignarLineaPendienteFactura(facturaId,linea.indice,expedienteId),onSuccess:()=>onDone()});
  return <div className="invoice-pending-assignment"><div className="invoice-pending-assignment__identity"><TriangleAlert size={17}/><div><strong>{linea.matricula||"Sin matricula detectada"}</strong><small>{linea.documento}</small></div></div><div className="invoice-correction invoice-correction--pending"><div className="invoice-correction__input"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} placeholder="Buscar matricula, interesado o EXP-ID"/></div>{query.trim().length>=2?<div className="invoice-correction__results invoice-correction__results--inline">{search.isLoading?<small>Buscando...</small>:search.data?.expedientes.length?search.data.expedientes.map(item=>{const expedienteId=Number(item.id.replace(/\D/g,""));return <button key={item.id} type="button" disabled={mutation.isPending} onClick={()=>mutation.mutate(expedienteId)}><strong>{item.titulo} · {item.id}</strong><small>{item.detalle} · {item.meta}</small></button>}):<small>Sin coincidencias.</small>}</div>:null}{mutation.isError?<small className="invoice-correction__error">{mutation.error instanceof ApiError&&mutation.error.details?mutation.error.details:"No se pudo asignar la linea."}</small>:null}</div></div>;
}
export function FacturaDetailPage(){
  const {id}=useParams(); const facturaId=Number(id); const {user}=useOutletContext<AppOutletContext>(); const qc=useQueryClient(); const navigate=useNavigate();
  const {confirm,dialog}=useConfirmDialog();
  const remove=useMutation({mutationFn:()=>eliminarFactura(facturaId),onSuccess:async()=>{await qc.invalidateQueries({queryKey:["facturas"]});navigate("/facturas")}});
  const query=useQuery({queryKey:["factura-detalle",facturaId],queryFn:()=>obtenerFacturaDetalle(facturaId),enabled:Number.isFinite(facturaId)});
  const uploadReceipt=useMutation({mutationFn:(archivo:File)=>aportarComprobante(facturaId,archivo),onSuccess:()=>query.refetch()});
  if(query.isLoading)return <section className="invoice-detail"><div className="empty-state">Cargando factura…</div></section>;
  if(query.isError||!query.data)return <section className="invoice-detail"><div className="alert alert--danger">No se pudo abrir la factura.</div><Link className="soft-button" to="/facturas"><ArrowLeft size={16}/> Volver</Link></section>;
  const {factura,vinculaciones,lineasPendientes}=query.data;
  if(user?.rol==="CLIENTE"){
    const moneda=factura.moneda||"EUR";
    const formato=(valor:number)=>new Intl.NumberFormat("es-ES",{style:"currency",currency:moneda}).format(valor||0);
    const pendiente=Math.max(0,(factura.total||0)-(factura.importePagado||0));
    const estados={PENDIENTE:"Pendiente de pago",PARCIALMENTE_PAGADA:"Pago parcial",PAGADA:"Pagada",ANULADA:"Anulada"};
    return <section className="client-invoice-detail">
      <header className="client-invoice-detail__hero"><div><Link to={vinculaciones[0]?`/expedientes/${vinculaciones[0].expedienteId}`:"/facturas"}><ArrowLeft size={15}/> Volver al expediente</Link><p className="eyebrow">Factura del expediente</p><h2>{factura.numero||`Factura #${factura.id}`}</h2><p>{factura.contactoNombre||"Cliente"}{factura.contactoNif?` ? ${factura.contactoNif}`:""}</p></div><button className="primary-button" onClick={()=>abrirPdf(factura.id)}><Download size={16}/> Abrir factura PDF</button></header>
      <div className="client-invoice-detail__totals"><article><ReceiptText size={18}/><span>Total factura</span><strong>{formato(factura.total)}</strong></article><article><WalletCards size={18}/><span>Importe pagado</span><strong>{formato(factura.importePagado)}</strong></article><article className={pendiente>0?"is-pending":"is-paid"}><span>Pendiente</span><strong>{formato(pendiente)}</strong><small>{estados[factura.estado]}</small></article></div>
      <div className="client-invoice-detail__grid"><section className="client-invoice-card"><header><div><p className="eyebrow">Datos de emisi?n</p><h3>Detalle de la factura</h3></div><CalendarDays size={19}/></header><dl><div><dt>Fecha de emisi?n</dt><dd>{factura.fechaEmision?new Date(`${factura.fechaEmision}T00:00:00`).toLocaleDateString("es-ES"):"No disponible"}</dd></div><div><dt>Vencimiento</dt><dd>{factura.fechaVencimiento?new Date(`${factura.fechaVencimiento}T00:00:00`).toLocaleDateString("es-ES"):"No indicado"}</dd></div><div><dt>Estado</dt><dd><span className={`invoice-state invoice-state--${factura.estado.toLowerCase()}`}>{estados[factura.estado]}</span></dd></div></dl><div className="client-invoice-expedientes"><span>Expedientes incluidos</span>{vinculaciones.map(v=><Link key={v.id} to={`/expedientes/${v.expedienteId}`}><strong>{v.matricula||`EXP-${v.expedienteId}`}</strong><small>EXP-{v.expedienteId}</small></Link>)}</div></section>
      <section className="client-invoice-card client-invoice-receipts"><header><div><p className="eyebrow">Justificantes</p><h3>Comprobantes de pago</h3></div><ShieldCheck size={19}/></header>{factura.comprobantes.length?<div className="client-receipt-list">{factura.comprobantes.map(c=><button key={c.id} type="button" onClick={()=>abrirComprobante(c.id)}><span><strong>{c.nombreOriginal}</strong><small>{new Date(c.creadoEn).toLocaleDateString("es-ES")}</small></span><span className={`client-receipt-state client-receipt-state--${c.estado.toLowerCase()}`}>{c.estado==="VERIFICADO"?"Verificado":c.estado==="DESCARTADO"?"Descartado":"En revisi?n"}</span></button>)}</div>:<div className="empty-state">Todav?a no hay comprobantes aportados.</div>}<label className={`soft-button client-receipt-upload${uploadReceipt.isPending?" is-disabled":""}`}><FileUp size={16}/>{uploadReceipt.isPending?"Subiendo?":"Aportar comprobante"}<input hidden disabled={uploadReceipt.isPending} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];e.currentTarget.value="";if(file)uploadReceipt.mutate(file)}}/></label>{uploadReceipt.isError?<div className="alert alert--danger">No se pudo aportar el comprobante.</div>:null}</section></div>
    </section>;
  }
  const handleDelete=async()=>{const accepted=await confirm({title:"Eliminar factura",description:"Se eliminaran el PDF y todas sus asignaciones a expedientes. Esta accion no se puede deshacer.",confirmLabel:"Eliminar factura",tone:"danger"});if(accepted)remove.mutate()};
  return <section className="invoice-detail"><header className="invoice-detail__header"><div><Link to="/facturas"><ArrowLeft size={15}/> Facturas</Link><p className="eyebrow">Conciliación guardada</p><h2>{factura.numero||`Factura #${factura.id}`}</h2><p>{factura.contactoNombre||"Sin cliente"} · {factura.fechaEmision?new Date(`${factura.fechaEmision}T00:00:00`).toLocaleDateString("es-ES"):"Fecha no disponible"}</p></div><div className="invoice-detail__actions"><button className="soft-button" onClick={()=>abrirPdf(factura.id)}><Download size={16}/> Abrir PDF</button>{user?.rol==="ADMIN"&&factura.eliminable?<button className="soft-button soft-button--danger" disabled={remove.isPending} onClick={()=>void handleDelete()}><Trash2 size={16}/>{remove.isPending?"Eliminando...":"Eliminar factura"}</button>:null}</div></header>{remove.isError?<div className="alert alert--danger">{remove.error instanceof ApiError&&remove.error.details?remove.error.details:"No se pudo eliminar la factura."}</div>:null}
    {lineasPendientes.length?<div className="invoice-detail__pending-section"><div className="invoice-detail__pending"><TriangleAlert size={19}/><div><strong>{lineasPendientes.length} {lineasPendientes.length===1?"línea pendiente":"líneas pendientes"}</strong><span>Selecciona el expediente correcto para completar la conciliación.</span></div></div><div className="invoice-pending-list">{lineasPendientes.map(linea=><AsignarPendiente key={`${linea.indice}-${linea.documento}`} facturaId={facturaId} linea={linea} onDone={()=>{void query.refetch();void qc.invalidateQueries({queryKey:["facturas"]})}}/>)}</div></div>:<div className="invoice-detail__complete"><ShieldCheck size={18}/><span>Todas las líneas registradas están asignadas.</span></div>}
    <div className="invoice-detail__section"><header><div><h3>Expedientes asignados</h3><p>{vinculaciones.length} vinculaciones guardadas</p></div></header>{vinculaciones.length?<div className="invoice-links-table"><div className="invoice-links-table__head"><span>Expediente</span><span>Datos detectados</span><span>Estado</span><span></span></div>{vinculaciones.map(v=><div className="invoice-links-table__row" key={v.id}><div><strong>{v.matricula||`EXP-${v.expedienteId}`}</strong><small>EXP-{v.expedienteId} · {v.cliente}</small></div><div><span>{v.matriculaDetectada||"Sin matrícula detectada"}</span><small>{v.compradorIdentificadorDetectado||"Comprador no detectado"}{v.bastidorDetectado?` · ${v.bastidorDetectado}`:""}</small></div><div><span className="invoice-link-state"><Check size={13}/>{v.estadoVinculacion.toLowerCase().replaceAll("_"," ")}</span><small>{v.confianza}% confianza</small>{v.motivoRevision?<small>{v.motivoRevision}</small>:null}</div><div>{user?.rol==="ADMIN"?<CorregirExpediente facturaId={facturaId} vinculacion={v} onDone={()=>{void query.refetch();void qc.invalidateQueries({queryKey:["facturas"]})}}/>:null}</div></div>)}</div>:<div className="empty-state">Todavía no hay expedientes vinculados.</div>}</div>
    {dialog}
  </section>;
}